language: node_js
node_js:
- 12.19.0
before_install:
- npm i -g npm@6.14.8
install:
- npm install chai
- npm install mocha
- npm install express
- npm install body-parser
- npm install cookie-parser
- npm install multer
- npm install stylus
- npm install nib
- npm install method-override
- npm install express-session
- npm install supervisor
- npm install node-xlsx
- npm install mongoose
- npm install dotenv
- npm install mongodb
- npm install async
- npm install mongoose-history
- npm install pug
- npm install nodemon
- npm install browser-sync
deploy:
  provider: heroku
  api_key:
    secure: CArauXM6uCtk3IVJdzkYNrU/OYYF1a5+rcEsNOptNERxUmK04d5hM+duo8WsUip0bTTNhyG2PWjOX9hoctbgOYyQeVkpCtHn8AXH1RQxGiAhjbbUvtmDRBxkFHln3eoWWSZ0KhTlPOt1iTA+h1fthNmnpf1pDRT3zA4Ocki6sjorVGz9EkVHc838u8ROKq7VJ3l1xqp9gvrBvpLE6YYUwkg1NoYCXeaFsIVJRz2AF766cR33mPjsADU9fdZEsfOvrgtSCDT6V4O2TdMClFwaGsjesomVq/sr0CfRWzBJAdWYpiK4Ujnzof8g1s24nZEj3aXcRSR5vM/q2X13n+30HMpHb7ykYmrFoanZs7vOA6Jf/QXmOkZQxcT1671HLNHHfq6nCOjvrX7Sd9g9f0xx5vcUE9yWlRtoRDE96YXTFd47jxa3UvffKMrVOR7C78Ii6/O8rODkgE0ZuFppoFfsaP5DuBxITp1FPbgO6SYIJhYAMn/O3QWigRIfpfIunZg9bliSLT6jcaiO6hUUvWS3KZ+h1K2pyhQDXGnXEvYu7sRx62tYrQo27/nICyhMGns0o4dgpnGpyMUzVKIvRDskOMXEaWymd4/wY6AV+8nsQ/r+XLF6IN8dKd7/KA+BN1QMEFfDvNjfp8FWNlmzy642t3X0tCk4WAwrOmJQloUIEKk=
  app: vt-team-manager
  on:
    repo: tinel-c/vt-team-manager
  strategy: git