language: node_js
node_js:
- 12.19.0
before_install:
- npm i -g npm@6.14.8
install:
- npm install chai
- npm install mocha
- npm install express
- npm install body-parser
- npm install cookie-parser
- npm install multer
- npm install stylus
- npm install nib
- npm install method-override
- npm install express-session
- npm install supervisor
- npm install node-xlsx
- npm install mongoose
- npm install dotenv
- npm install mongodb
- npm install async
- npm install mongoose-history
- npm install pug
- npm install nodemon
- npm install browser-sync
deploy:
  provider: heroku
  api_key:
    secure: EM7z+BC21makn0LUt7iGt7aeeS9gNVsKa+a4XSX8QYbeFUWW4P3Ha0ec8BBTcLPDasxqwb2OJgAMGoLN3mnQUjMuUTq885gqI8I5NYhRFu9sLYwCL4/cIv8VlvKlecREvep1zsNltNNAidU7VVOkVyuWdRY0xw8exlPxA7D/An597CSVqElorutp87r8DH95uAh0Fu/cWRbKBnzyv9WuKYM8k98ldHwpwHxrNv409dp3sdATJqTy2caAYQyBTHlw+G3ZtE3t2TZ3pG/7v+Ux5o27sNGvm7xcDs77njn7c30aMGqRheO+GvQ/KWEGC5VZSsYIrHSzfb/PDdfj2L5tsns9WKoa5PKjmsutI0MGY/gXnmgtGahSWa7GASdRyF1m/KImShjsPQLprXIUIqd21FQQZUkarZnM+uIIJrYUJAudlDuNXKnO7+M2lVr1XSXn9FNzOSZlQkSo7wwy2DaCxpGFnOEN6I59GMnEXmuWVUm8/fgt51bm1zpCh8iIsSQyqws4TM6xYnBNDiuTufzSh72fNcsMrMQVhyWUYrtTxq4G0vasRH2rV9yfeWyivZO4aCRheZ78vczco91RpIZXcaZGN+ClpGoy99ywX4pgFXxP14bHZot+7BqU0GmZVd4mLON6eiyDhFa7Kow4/Ft1ylycNi+AQ7B7HzN5QZhuA6k=
  app: vt-team-manager
  on:
    repo: tinel-c/vt-team-manager
  strategy: git
